numIters: 2
numEps: 10
tempThreshold: 15
updateThreshold: 0.1
maxlenOfQueue: 200000
numMCTSSims: 30
arenaCompare: 4
cpuct: 0.5
checkpoint: ./temp2/
load_model: false
load_folder_file:
  - ./temp2/
  - best.pth.tar
numItersForTrainExamplesHistory: 20
